### ISSUE TITLE
issue with tabbar controller

### ISSUE THREAD

**Issue by DKalachniuk** [younatics/ExpandableCell#64]
I have a tabbar controller. 
ViewController A with expandable table view inside
View Controller B without. Just empty one

I open A.
opened B
then Open A

expandable table view is not working and crashes

I reproduced this issue with demo app. Just embed in tabbarcontroller instead of navigation controller.
please help

**Comment by pikaboo** [comment]
Hi, 
Do you have a link to your reproduction code? So I may take a look? 

Thanks,

**Comment by DKalachniuk** [comment]
no. But I can create a repo. one sec

**Comment by DKalachniuk** [comment]
https://github.com/DKalachniuk/ExpandableCell

please take a look
Thank you

**Comment by pikaboo** [comment]
Ok I found how to fix your problem:

Because of a memory leak in certain conditions, I added a flow to allow auto release of delegate - in some cases it is OK to have it auto released, i.e the screen will reload and the delegate will be reset automatically.

However, in your case, the screen doesn't reload - i.e viewDidLoad does not get called when you switch between tabs, so your scenario doesnt need the autoRelease of the delegate, you need to manage it yourself (i.e when to add it and when to remove it from the tableview).

so in your viewDidLoad add this code:
        tableView.autoReleaseDelegate = false

and that way your delegate will get to live past viewWillMoveToWindow:nil

however, when you leave that screen - where the tabs are- to have completely disappear from memory, you'd need to make the delegate be nil yourself

**Comment by DKalachniuk** [comment]
it works! Thank you very much!  

> `however, when you leave that screen - where the tabs are- to have completely disappear from memory, you'd need to make the delegate be nil yourself`

Can you please explain again this
